export const AUTH_USER = 'AUTH_USER';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_START = 'USER_AUTH_START';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SINGUP_FAIL = 'USER_SIGNUP_FAIL';
export const USER_AUTH_CHECK_TIMEOUT = 'USER_AUTH_CHECK_TIMEOUT';
export const SET_USER_AUTH_REDIRECT_PATH = 'SET_USER_AUTH_REDIRECT_PATH';
export const USER_AUTH_CHECK_STATE = 'USER_AUTH_CHECK_STATE';
export const DISPLAY_TOSTER='DISPLAY_TOSTER';
export const TOSTER_MESSAGE_RESET='TOSTER_MESSAGE_RESET';
