//User Auth Initialize
export const AUTH_USER = 'AUTH_USER';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_START = 'USER_AUTH_START';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
//Other Constant
export const USER_AUTH_CHECK_TIMEOUT = 'USER_AUTH_CHECK_TIMEOUT';
export const SET_USER_AUTH_REDIRECT_PATH = 'SET_USER_AUTH_REDIRECT_PATH';
export const USER_AUTH_CHECK_STATE = 'USER_AUTH_CHECK_STATE';
//User Auth Logout
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';
export const USER_AUTH_INITIATE_LOGOUT = 'USER_AUTH_INITIATE_LOGOUT';
//User Auth Login
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'; 
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
//User Auth Signup
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SINGUP_FAIL = 'USER_SIGNUP_FAIL';
//Display Toster in User Face
export const DISPLAY_TOSTER='DISPLAY_TOSTER';
export const TOSTER_MESSAGE_RESET='TOSTER_MESSAGE_RESET';
//Fetch service from server
export const CUSTOMER_FETCH_SERVICE = 'CUSTOMER_FETCH_SERVICE';
export const CUSTOMER_FETCH_SERVICE_SUCCESS = 'CUSTOMER_FETCH_SERVICE_SUCCESS';
export const CUSTOMER_FETCH_SERVICE_FAIL = 'CUSTOMER_FETCH_SERVICE_FAIL';

