export const ADMIN_AUTH_USER = 'ADMIN_AUTH_USER';
export const ADMIN_AUTH_FAIL = 'ADMIN_AUTH_FAIL';
export const ADMIN_AUTH_START = 'ADMIN_AUTH_START';
export const ADMIN_AUTH_LOGOUT = 'ADMIN_AUTH_LOGOUT';
export const ADMIN_AUTH_SUCCESS = 'ADMIN_AUTH_SUCCESS';
export const ADMIN_AUTH_CHECK_STATE = 'ADMIN_AUTH_CHECK_STATE';
export const ADMIN_AUTH_CHECK_TIMEOUT = 'ADMIN_AUTH_CHECK_TIMEOUT';
export const ADMIN_AUTH_INITIATE_LOGOUT = 'ADMIN_AUTH_INITIATE_LOGOUT';
export const SET_ADMIN_AUTH_REDIRECT_PATH = 'SET_ADMIN_AUTH_REDIRECT_PATH';

export const ADMIN_AUTH_FORGOT = 'ADMIN_AUTH_FORGOT';
export const ADMIN_AUTH_FORGOT_SUCCESS = 'ADMIN_AUTH_FORGOT_SUCCESS';
export const ADMIN_AUTH_FORGOT_FAIL = 'ADMIN_AUTH_FORGOT_FAIL';

export const ADMIN_AUTH_RESET = 'ADMIN_AUTH_RESET';
export const ADMIN_RESET_SUCCESS = 'ADMIN_RESET_SUCCESS';
export const ADMIN_RESET_FAIL = 'ADMIN_RESET_FAIL';

export const ADMIN_UPDATE_SITE_SETTING = 'ADMIN_UPDATE_SITE_SETTING';
export const ADMIN_UPDATE_SITE_SETTING_SUCCESS = 'ADMIN_UPDATE_SITE_SETTING_SUCCESS';
export const ADMIN_UPDATE_SITE_SETTING_FAIL = 'ADMIN_UPDATE_SITE_SETTING_FAIL';

export const ADMIN_FETCH_SITE_SETTING = 'ADMIN_FETCH_SITE_SETTING';
export const ADMIN_FETCH_SITE_SETTING_SUCCESS = 'ADMIN_FETCH_SITE_SETTING_SUCCESS';
export const ADMIN_FETCH_SITE_SETTING_FAIL = 'ADMIN_FETCH_SITE_SETTING_FAIL';

export const ADMIN_ADD_CMS = 'ADMIN_ADD_CMS';
export const ADMIN_ADD_CMS_SUCCESS = 'ADMIN_ADD_CMS_SUCCESS';
export const ADMIN_ADD_CMS_FAIL = 'ADMIN_ADD_CMS_FAIL';

export const ADMIN_FETCH_CMS = 'ADMIN_FETCH_CMS';
export const ADMIN_FETCH_CMS_SUCCESS = 'ADMIN_FETCH_CMS_SUCCESS';
export const ADMIN_FETCH_CMS_FAIL = 'ADMIN_FETCH_CMS_FAIL';

export const ADMIN_FETCH_SINGLE_CMS = 'ADMIN_FETCH_SINGLE_CMS';
export const ADMIN_FETCH_SINGLE_CMS_SUCCESS = 'ADMIN_FETCH_SINGLE_CMS_SUCCESS';
export const ADMIN_FETCH_SINGLE_CMS_FAIL = 'ADMIN_FETCH_SINGLE_CMS_FAIL';

export const ADMIN_UPDATE_CMS = 'ADMIN_UPDATE_CMS';
export const ADMIN_UPDATE_CMS_SUCCESS = 'ADMIN_UPDATE_CMS_SUCCESS';
export const ADMIN_UPDATE_CMS_FAIL = 'ADMIN_UPDATE_CMS_FAIL';

export const ADMIN_ADD_SERVICE = 'ADMIN_ADD_SERVICE';
export const ADMIN_ADD_SERVICE_SUCCESS = 'ADMIN_ADD_SERVICE_SUCCESS';
export const ADMIN_ADD_SERVICE_FAIL = 'ADMIN_ADD_SERVICE_FAIL';

export const ADMIN_FETCH_SERVICE = 'ADMIN_FETCH_SERVICE';
export const ADMIN_FETCH_SERVICE_SUCCESS = 'ADMIN_FETCH_SERVICE_SUCCESS';
export const ADMIN_FETCH_SERVICE_FAIL = 'ADMIN_FETCH_SERVICE_FAIL';

export const ADMIN_FETCH_SINGLE_SERVICE = 'ADMIN_FETCH_SINGLE_SERVICE';
export const ADMIN_FETCH_SINGLE_SERVICE_SUCCESS = 'ADMIN_FETCH_SINGLE_SERVICE_SUCCESS';
export const ADMIN_FETCH_SINGLE_SERVICE_FAIL = 'ADMIN_FETCH_SINGLE_SERVICE_FAIL';

export const ADMIN_UPDATE_SERVICE = 'ADMIN_UPDATE_SERVICE';
export const ADMIN_UPDATE_SERVICE_SUCCESS = 'ADMIN_UPDATE_SERVICE_SUCCESS';
export const ADMIN_UPDATE_SERVICE_FAIL = 'ADMIN_UPDATE_SERVICE_FAIL';

//Action for fetching message
export const ADMIN_FETCH_MESSAGES = 'ADMIN_FETCH_MESSAGES';
export const ADMIN_FETCH_MESSAGE_SUCCESS = 'ADMIN_FETCH_MESSAGE_SUCCESS';
export const ADMIN_FETCH_MESSAGE_FAIL = 'ADMIN_FETCH_MESSAGE_FAIL';
export const ADMIN_FETCH_SINGLE_MESSAGE = 'ADMIN_FETCH_SINGLE_MESSAGE';
export const ADMIN_FETCH_SINGLE_MESSAGE_SUCCESS = 'ADMIN_FETCH_SINGLE_MESSAGE_SUCCESS';
export const ADMIN_FETCH_SINGLE_MESSAGE_FAIL = 'ADMIN_FETCH_SINGLE_MESSAGE_FAIL';
export const ADMIN_UPDATE_MESSAGE = 'ADMIN_UPDATE_MESSAGE';
export const ADMIN_UPDATE_MESSAGE_SUCCESS = 'ADMIN_UPDATE_MESSAGE_SUCCESS';
export const ADMIN_UPDATE_MESSAGE_FAIL = 'ADMIN_UPDATE_MESSAGE_FAIL';