export const ADMIN_AUTH_USER = 'ADMIN_AUTH_USER';
export const ADMIN_AUTH_FAIL = 'ADMIN_AUTH_FAIL';
export const ADMIN_AUTH_START = 'ADMIN_AUTH_START';
export const ADMIN_AUTH_LOGOUT = 'ADMIN_AUTH_LOGOUT';
export const ADMIN_AUTH_SUCCESS = 'ADMIN_AUTH_SUCCESS';
export const ADMIN_AUTH_CHECK_STATE = 'ADMIN_AUTH_CHECK_STATE';
export const ADMIN_AUTH_CHECK_TIMEOUT = 'ADMIN_AUTH_CHECK_TIMEOUT';
export const ADMIN_AUTH_INITIATE_LOGOUT = 'ADMIN_AUTH_INITIATE_LOGOUT';
export const SET_ADMIN_AUTH_REDIRECT_PATH = 'SET_ADMIN_AUTH_REDIRECT_PATH';

export const ADMIN_AUTH_FORGOT = 'ADMIN_AUTH_FORGOT';
export const ADMIN_AUTH_FORGOT_SUCCESS = 'ADMIN_AUTH_FORGOT_SUCCESS';
export const ADMIN_AUTH_FORGOT_FAIL = 'ADMIN_AUTH_FORGOT_FAIL';

export const ADMIN_AUTH_RESET = 'ADMIN_AUTH_RESET';
export const ADMIN_RESET_SUCCESS = 'ADMIN_RESET_SUCCESS';
export const ADMIN_RESET_FAIL = 'ADMIN_RESET_FAIL';